import 'modules/admin-lte/plugins/jquery-ui/jquery-ui.min'
import 'modules/admin-lte/plugins/fastclick/fastclick'
import 'modules/admin-lte/dist/js/adminlte'
import 'modules/admin-lte/plugins/jquery/jquery.min'
import 'admin-lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'
import 'admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars'
import 'admin-lte/plugins/overlayScrollbars/js/OverlayScrollbars'

import 'admin-lte/plugins/fontawesome-free/css/all.min.css'
import 'modules/admin-lte/dist/css/adminlte.min.css'
import 'modules/admin-lte/plugins/jquery-knob/jquery.knob.min'
import 'modules/admin-lte/plugins/jqvmap/jquery.vmap.min'
import 'modules/admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min'
import 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css'

import './custom.css'